# Generated by Django 5.0.1 on 2024-01-03 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='usuario',
            field=models.CharField(default='', max_length=50),
        ),
    ]
