# Generated by Django 5.0.1 on 2024-01-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0002_formulario_fecha_ingreso_formulario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='anioNacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
    ]
