# Generated by Django 5.0.1 on 2024-01-08 12:12

import botApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0003_alter_formulario_anionacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anioNacimiento', models.DateField(validators=[botApp.models.Respuesta.validate_fecha_nacimiento], verbose_name='Fecha de Nacimiento')),
                ('usuario', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.comuna')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.genero')),
            ],
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
