# Generated by Django 5.0.1 on 2024-01-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0004_comuna_genero_respuesta_delete_formulario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='usuario',
            new_name='id_usuario',
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(choices=[('1', 'Femenino'), ('2', 'Masculino'), ('3', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
